#!/bin/bash
##############################################################################
#
# KPP Installation Script
# Automatically configures and builds KPP
#
##############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_header() {
    echo -e "\n${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}→ $1${NC}"
}

# Main installation
print_header "KPP Installation Script"

# Get KPP_HOME directory
KPP_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
print_info "KPP installation directory: $KPP_HOME"

# Step 1: Check for required tools
print_header "Step 1: Checking requirements"

# Check for gcc/cc
if command -v gcc &> /dev/null; then
    CC="gcc"
    print_success "Found gcc compiler: $(which gcc)"
elif command -v cc &> /dev/null; then
    CC="cc"
    print_success "Found cc compiler: $(which cc)"
else
    print_error "No C compiler found (gcc or cc required)"
    exit 1
fi

# Check for flex
if command -v flex &> /dev/null; then
    FLEX="flex"
    print_success "Found flex: $(which flex)"
else
    print_error "flex not found. Please install flex first:"
    echo "  Ubuntu/Debian: sudo apt-get install flex"
    echo "  RedHat/CentOS: sudo yum install flex"
    echo "  macOS: brew install flex"
    exit 1
fi

# Check for yacc/bison
if command -v yacc &> /dev/null || command -v bison &> /dev/null; then
    print_success "Found yacc/bison"
else
    print_error "yacc/bison not found. Please install bison first:"
    echo "  Ubuntu/Debian: sudo apt-get install bison"
    echo "  RedHat/CentOS: sudo yum install bison"
    echo "  macOS: brew install bison"
    exit 1
fi

# Step 2: Detect flex library location
print_header "Step 2: Detecting flex library location"

FLEX_LIB_DIR=""
for dir in /usr/lib /usr/lib64 /usr/lib/x86_64-linux-gnu /usr/local/lib /opt/homebrew/lib; do
    if [ -f "$dir/libfl.a" ] || [ -f "$dir/libfl.so" ]; then
        FLEX_LIB_DIR="$dir"
        break
    fi
done

if [ -z "$FLEX_LIB_DIR" ]; then
    print_error "Could not find flex library (libfl.a or libfl.so)"
    print_info "Trying to continue anyway (might work on some systems)..."
    FLEX_LIB_DIR="/usr/lib"
else
    print_success "Found flex library in: $FLEX_LIB_DIR"
fi

# Detect include directory
if [ -d "/usr/include" ]; then
    INCLUDE_DIR="/usr/include"
elif [ -d "/usr/include/sys" ]; then
    INCLUDE_DIR="/usr/include/sys"
else
    INCLUDE_DIR="/usr/include"
fi
print_success "Include directory: $INCLUDE_DIR"

# Step 3: Configure Makefile.defs
print_header "Step 3: Configuring Makefile.defs"

# Backup original if it exists
if [ -f "$KPP_HOME/Makefile.defs" ]; then
    cp "$KPP_HOME/Makefile.defs" "$KPP_HOME/Makefile.defs.backup"
    print_info "Backed up existing Makefile.defs to Makefile.defs.backup"
fi

# Create Makefile.defs with detected settings
cat > "$KPP_HOME/Makefile.defs" << EOF
# -*- sh -*-
##############################################################################
# KPP Makefile Configuration
# Auto-generated by install.sh on $(date)
##############################################################################

# C Compiler
CC=$CC

# Flex lexical analyzer
FLEX=$FLEX

# Flex library directory
FLEX_LIB_DIR=$FLEX_LIB_DIR

# Compiler flags
CC_FLAGS=-O2 -Wall

# Include directory
INCLUDE_DIR=$INCLUDE_DIR

##############################################################################
EOF

print_success "Created Makefile.defs with detected settings"

# Step 4: Build KPP
print_header "Step 4: Building KPP"

cd "$KPP_HOME"
if make clean &> /dev/null; then
    print_info "Cleaned previous build"
fi

print_info "Compiling KPP (this may take a moment)..."
if make > build.log 2>&1; then
    print_success "KPP compiled successfully"
else
    print_error "Compilation failed. Check build.log for details"
    tail -20 build.log
    exit 1
fi

# Check if binary was created
if [ -f "$KPP_HOME/bin/kpp" ]; then
    print_success "KPP binary created: $KPP_HOME/bin/kpp"
else
    print_error "KPP binary not found after build"
    exit 1
fi

# Step 5: Setup environment
print_header "Step 5: Environment setup"

SHELL_RC=""
if [ -n "$BASH_VERSION" ]; then
    SHELL_RC="$HOME/.bashrc"
elif [ -n "$ZSH_VERSION" ]; then
    SHELL_RC="$HOME/.zshrc"
else
    SHELL_RC="$HOME/.profile"
fi

print_info "Detected shell configuration file: $SHELL_RC"

# Check if already configured
if grep -q "KPP_HOME" "$SHELL_RC" 2>/dev/null; then
    print_info "KPP_HOME already set in $SHELL_RC"
else
    echo "" >> "$SHELL_RC"
    echo "# KPP - Kinetic PreProcessor" >> "$SHELL_RC"
    echo "export KPP_HOME=\"$KPP_HOME\"" >> "$SHELL_RC"
    echo "export PATH=\"\$PATH:\$KPP_HOME/bin\"" >> "$SHELL_RC"
    print_success "Added KPP_HOME and PATH to $SHELL_RC"
fi

# Set for current session
export KPP_HOME="$KPP_HOME"
export PATH="$PATH:$KPP_HOME/bin"

# Step 6: Test installation
print_header "Step 6: Testing installation"

# Test --version
if "$KPP_HOME/bin/kpp" --version &> /dev/null; then
    print_success "KPP --version works"
else
    print_error "KPP --version failed"
    exit 1
fi

# Test --help
if "$KPP_HOME/bin/kpp" --help &> /dev/null; then
    print_success "KPP --help works"
else
    print_error "KPP --help failed"
    exit 1
fi

# Test --list-models
if "$KPP_HOME/bin/kpp" --list-models &> /dev/null; then
    print_success "KPP --list-models works"
else
    print_error "KPP --list-models failed"
    exit 1
fi

# Success!
print_header "Installation Complete!"

cat << EOF
${GREEN}✓ KPP has been successfully installed!${NC}

Installation location: $KPP_HOME
Binary location: $KPP_HOME/bin/kpp

To use KPP in this session, run:
  ${YELLOW}export KPP_HOME="$KPP_HOME"${NC}
  ${YELLOW}export PATH="\$PATH:\$KPP_HOME/bin"${NC}

Or start a new terminal session (environment already configured in $SHELL_RC)

Quick start:
  ${BLUE}kpp --help${NC}              Show help message
  ${BLUE}kpp --list-models${NC}       List available models
  ${BLUE}kpp --list-integrators${NC}  List available integrators
  ${BLUE}kpp mymodel.kpp${NC}         Process your KPP file

Example files are in: $KPP_HOME/demo/examples/

${GREEN}Happy modeling!${NC}

EOF
